# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.
# What standard to use. This is optional and defaults to VHDL2008.
standard = "2008"

[libraries]

# Defines library lib2
lib2.files = [
  '**/*.vhd'
]

# Defines library lib1
#lib1.files = [
#  'pkg1.vhd',
 # 'tb_ent.vhd',
#]

# Libraries can be marked as third-party to disable some analysis warnings, such as unused declarations
#UNISIM.files = [
#  'C:\Xilinx\Vivado\2023.1\data\vhdl\src\unisims\unisim_VCOMP.vhd',
#]
#UNISIM.is_third_party = true
